a: a.cpp
	g++ -std=c++14 -Wall -g a.cpp -o a.out

b: b.cpp
	g++ -std=c++14 -Wall -g b.cpp -o b.out

c: c.cpp
	g++ -std=c++14 -Wall -g c.cpp -o c.out

d: d.cpp
	g++ -std=c++14 -Wall -g d.cpp -o d.out

e: e.cpp
	g++ -std=c++14 -Wall -g e.cpp -o e.out
